"""
Applies Hungarian translations to transcript_hu_actions.xliff.
Edit the TRANSLATIONS dict below, then run: py translate_hu_actions.py
Strings not in the dict are left empty for manual review.
"""
import os
import re
from lxml import etree

XLIFF_PATH = os.path.join(os.path.dirname(__file__), '..', 'draft', 'hu', 'transcript_hu_actions.xliff')
NS = 'urn:oasis:names:tc:xliff:document:1.2'

# ── OSRS place names / proper nouns that stay in English ─────────────────────
KEEP_ENGLISH = {
    "Al Kharid", "Arceuus", "Arceuus spellbook", "Ancients", "Ancient spellbook",
    "Ancient", "Ardougne", "Barbarian Outpost", "Brimhaven", "Burthorpe",
    "Camelot", "Castle Wars", "Corporeal Beast", "Crafting Guild", "Cooking Guild",
    "Digsite", "Draynor Village", "Edgeville", "Emir's Arena", "Falador Park",
    "Farming Guild", "Ferox Enclave", "Fishing Guild", "Fortis Colosseum",
    "Fossil Island", "Grand Exchange", "Iceberg", "Inferno", "Island of Stone",
    "Jatizso", "Karamja", "Land's End", "Lithkren", "Mining Guild", "Miscellania",
    "Monastery", "Neitiznot", "Port Piscarilius", "Port Sarim", "Ranging Guild",
    "Rellekka", "Rimmington", "Seers'", "Seers' Village", "Tears of Guthix",
    "Turael", "Ungael", "Varrock", "Waterbirth Island", "Watchtower", "Watermill",
    "Weiss", "Wintertodt Camp", "Woodcutting Guild", "Yanille", "Zanaris",
    "Lunar", "Lunar spellbook", "Ironman Group", "Bond Pouch", "DPS",
    "Dondakan's Rock", "(Members)", "Pirate's Cove", "Warriors' Guild",
    "Champions' Guild", "Slayer", "Turael",
}

# ── Main translation dictionary ───────────────────────────────────────────────
# Format: "English source": "Magyar fordítás"
# Leave a value as "" to mark as needs-review (will stay empty in output).
TRANSLATIONS = {
    # ── Core actions ──────────────────────────────────────────────────────────
    "Attack":               "Támadás",
    "Talk-to":              "Megszólítás",
    "Talk to":              "Megszólítás",
    "Talk":                 "Megszólítás",
    "Talk-To":              "Megszólítás",
    "Talk-into":            "Rábeszélés",
    "Examine":              "Vizsgálat",
    "Use":                  "Használat",
    "Take":                 "Felvétel",
    "Drop":                 "Eldobás",
    "Eat":                  "Evés",
    "Eat-from":             "Evés innen",
    "Drink":                "Ivás",
    "Drink-from":           "Ivás innen",
    "Wear":                 "Felöltés",
    "Wield":                "Forgatás",
    "Equip":                "Felszerelés",
    "Remove":               "Eltávolítás",
    "Open":                 "Megnyitás",
    "Open (normal)":        "Megnyitás (normál)",
    "Open (private)":       "Megnyitás (privát)",
    "Close":                "Bezárás",
    "Read":                 "Olvasás",
    "Read (Awakened)":      "Olvasás (Felébredt)",
    "Bank":                 "Bank",
    "Deposit":              "Betét",
    "Withdraw":             "Kivétel",
    "Trade":                "Kereskedés",
    "Trade with":           "Kereskedés",
    "Trade-with":           "Kereskedés",
    "Trade-in":             "Becserélés",
    "Buy":                  "Vásárlás",
    "Sell":                 "Eladás",
    "Pay":                  "Fizetés",
    "Pay-fare":             "Viteldíj fizetése",
    "Pay-Fare":             "Viteldíj fizetése",

    # ── Movement ──────────────────────────────────────────────────────────────
    "Climb":                "Mászás",
    "Climb up":             "Felmászás",
    "Climb down":           "Lemászás",
    "Climb Up":             "Felmászás",
    "Climb Down":           "Lemászás",
    "Climb-up":             "Felmászás",
    "Climb-down":           "Lemászás",
    "Climb-down (normal)":  "Lemászás (normál)",
    "Climb-down (private)": "Lemászás (privát)",
    "Climb-into":           "Bemászás",
    "Climb-off":            "Lemászás",
    "Climb-on":             "Felmászás",
    "Climb-over":           "Átmászás",
    "Climb-rope":           "Kötélmászás",
    "Climb-through":        "Átmászás",
    "Climb-through (normal)":  "Átmászás (normál)",
    "Climb-through (private)": "Átmászás (privát)",
    "Climb-to":             "Felmászás ide",
    "Climb-under":          "Alámászás",
    "Climb over":           "Átmászás",
    "Climb across":         "Átmászás",
    "Climb-across":         "Átmászás",
    "Cimb-down":            "Lemászás",
    "Climp-up":             "Felmászás",
    "Jump":                 "Ugrás",
    "Jump off":             "Leugrik",
    "Jump on":              "Felugrás",
    "Jump to":              "Ugrás ide",
    "Jump-Across":          "Átugrás",
    "Jump-Down":            "Leugrás",
    "Jump-Over":            "Átugrás",
    "Jump-To":              "Ugrás ide",
    "Jump-across":          "Átugrás",
    "Jump-down":            "Leugrás",
    "Jump-from":            "Leugrás",
    "Jump-in":              "Beugrás",
    "Jump-off":             "Leugrás",
    "Jump-on":              "Felugrás",
    "Jump-onto":            "Felugrás",
    "Jump-over":            "Átugrás",
    "Jump-through":         "Átjutás",
    "Jump-to":              "Ugrás ide",
    "Jump-up":              "Felugrás",
    "Leap":                 "Szökkenés",
    "Walk here":            "Séta ide",
    "Walk on":              "Átkelés",
    "Walk through":         "Áthaladás",
    "Walk-Down":            "Lemenetel",
    "Walk-Up":              "Felmenetel",
    "Walk-across":          "Átkelés",
    "Walk-along":           "Haladás",
    "Walk-down":            "Lemenetel",
    "Walk-on":              "Átkelés",
    "Walk-over":            "Átkelés",
    "Walk-past":            "Elhaladás",
    "Walk-through":         "Áthaladás",
    "Walk-to":              "Odamenetel",
    "Walk-up":              "Felmenetel",
    "Crawl":                "Kúszás",
    "Crawl through":        "Átbújás",
    "Crawl-down":           "Lebújás",
    "Crawl-through":        "Átbújás",
    "Crawl-under":          "Alábújás",
    "Cross":                "Átkelés",
    "Cross-bridge":         "Hídon átkelés",
    "Cross-over":           "Átkelés",
    "Cross-to":             "Átkelés ide",
    "Swim":                 "Úszás",
    "Swim to":              "Úszás ide",
    "Dive":                 "Merülés",
    "Dive in":              "Beugrás",
    "Slide":                "Csúszás",
    "Slide-along":          "Végigcsúszás",
    "Swing":                "Hintázás",
    "Swing Across":         "Átlendülés",
    "Swing across":         "Átlendülés",
    "Swing-across":         "Átlendülés",
    "Swing-from":           "Lendülés",
    "Swing-on":             "Hintázás",
    "Pass":                 "Áthaladás",
    "Pass (normal)":        "Áthaladás (normál)",
    "Pass (private)":       "Áthaladás (privát)",
    "Pass through":         "Áthaladás",
    "Pass-Through":         "Áthaladás",
    "Pass-through":         "Áthaladás",
    "Pass-to":              "Átadás",
    "Squeeze-Through":      "Átpréselés",
    "Squeeze-past":         "Elpréselés",
    "Squeeze-through":      "Átpréselés",
    "Enter":                "Belépés",
    "Enter-cloud":          "Belépés a felhőbe",
    "Enter-corrupted":      "Belépés (fertőzött)",
    "Enter-crypt":          "Belépés a kriptába",
    "Enter-guest":          "Belépés vendégként",
    "Enter-member":         "Belépés tagként",
    "Exit":                 "Kilépés",
    "Exit-cave":            "Kilépés a barlangból",
    "Exit-through":         "Kilépés erre",
    "Exit-through (Kourend)": "Kilépés erre (Kourend)",
    "Leave":                "Elhagyás",
    "Leave Cavern":         "Barlang elhagyása",
    "Leave House":          "Ház elhagyása",
    "Leave Tomb":           "Sír elhagyása",
    "Leave platform":       "Platform elhagyása",
    "Leave-area":           "Terület elhagyása",
    "Leave-group":          "Csoport elhagyása",
    "Leave-tutorial":       "Oktatóanyag elhagyása",
    "Descend":              "Leereszkedés",
    "Ascend":               "Feljutás",
    "Go-down":              "Lemenetel",
    "Go-inside":            "Bemenetel",
    "Go-through":           "Áthaladás",
    "Go-up":                "Felmenetel",
    "Climb through":        "Átbújás",
    "Board":                "Felszállás",
    "Deboard":              "Leszállás",
    "Disembark":            "Leszállás",
    "Ferry":                "Komp",
    "Travel":               "Utazás",
    "Travel to platform":   "Utazás a platformhoz",
    "Travel-End":           "Utazás vége",
    "Travel-Start":         "Utazás kezdete",
    "Transport":            "Szállítás",
    "Teleport":             "Teleportálás",
    "Teleport Menu":        "Teleport menü",
    "Teleport menu":        "Teleport menü",
    "Teleport to Destination": "Teleportálás célhoz",
    "Teleport to destination": "Teleportálás célhoz",

    # ── Combat ────────────────────────────────────────────────────────────────
    "Fight":                "Harc",
    "Fight-privately":      "Privát harc",
    "Kill":                 "Megölés",
    "Stab":                 "Szúrás",
    "Slash":                "Csapás",
    "Crush":                "Zúzás",
    "Bash":                 "Csapás",
    "Kick":                 "Rúgás",
    "Punch":                "Ökölcsapás",
    "Hit":                  "Ütés",
    "Strike":               "Ütés",
    "Block":                "Blokkolás",
    "Deflect":              "Kitérés",
    "Dodge":                "Kitérés",
    "Lunge":                "Szúrás",
    "Pummel":               "Püfölés",
    "Throw":                "Dobás",
    "Throw-at":             "Dobás ide",
    "Shoot":                "Lövés",
    "Shoot-at":             "Lövés ide",
    "Fire":                 "Tüzelés",
    "Fire!":                "Tűz!",
    "Fire-at":              "Tüzelés ide",
    "Impale":               "Felnyársal",
    "Lash":                 "Ostorcsapás",
    "Murder":               "Meggyilkolás",
    "Stun":                 "Elkábítás",
    "Bind":                 "Megkötözés",
    "Banish":               "Száműzés",
    "Dispel":               "Feloszlatás",
    "Conjure":              "Megidézés",
    "Summon":               "  Idézés",
    "Summon":               "Idézés",
    "Charge":               "Töltés",
    "Charge-at":            "Roham",
    "Intimidate":           "Megfélemlítés",
    "Threaten":             "Fenyegetés",
    "Insult":               "Sértegetés",
    "Taunt":                "Kihívás",
    "Challenge":            "Kihívás",
    "Challenge-mode":       "Kihívás mód",
    "Auto retaliate":       "Automatikus visszaütés",
    "Accurate":             "Pontos",
    "Aggressive":           "Agresszív",
    "Controlled":           "Irányított",
    "Defensive":            "Védekező",
    "Longrange":            "Hosszú hatótáv",
    "Rapid":                "Gyors",
    "Standard":             "Normál",
    "Standard Variant":     "Normál változat",
    "Maxhit Variant":       "Max sebzés változat",
    "Kill-count":           "Ölésszámláló",
    "Combat Options":       "Harci lehetőségek",

    # ── Skilling ──────────────────────────────────────────────────────────────
    "Chop":                 "Vágás",
    "Chop down":            "Kivágás",
    "Chop-down":            "Kivágás",
    "Cut":                  "Vágás",
    "Cut down":             "Kivágás",
    "Cut-Down":             "Kivágás",
    "Cut-branch":           "Ág vágása",
    "Cut-foot":             "Tő vágása",
    "Cut-vine":             "Inda vágása",
    "Cut-wood":             "Favágás",
    "Mine":                 "Bányászat",
    "Fish":                 "Halászat",
    "Fish-In":              "Halászat itt",
    "Cook":                 "Főzés",
    "Cook-at":              "Főzés itt",
    "Craft":                "Tárgy készítése",
    "Craft-goods":          "Áruk készítése",
    "Craft-rune":           "Rúna készítése",
    "Smith":                "Kovácsolás",
    "Smelt":                "Olvasztás",
    "Burn":                 "Égetés",
    "Burn-down":            "Leégetés",
    "Spin":                 "Fonás",
    "Weave":                "Szövés",
    "Tan-hides":            "Bőr cserzése",
    "Fletch":               "Nyílkészítés",
    "Plant":                "Ültetés",
    "Harvest":              "Aratás",
    "Rake":                 "Gereblyézés",
    "Weed":                 "Gyomlálás",
    "Water":                "Öntözés",
    "Prune":                "Nyírás",
    "Prune-back":           "Visszavágás",
    "Prune-sides":          "Oldalak nyírása",
    "Prune-top":            "Teteje nyírása",
    "Pick":                 "Szedés",
    "Pick up":              "Felvétel",
    "Pick-up":              "Felvétel",
    "Pickup":               "Felvétel",
    "Pick Banana":          "Banán szedése",
    "Pick Nuts":            "Dió szedése",
    "Pick-Fruit":           "Gyümölcs szedése",
    "Pick-Lock":            "Zárfeltörés",
    "Pick-apple":           "Alma szedése",
    "Pick-banana":          "Banán szedése",
    "Pick-coconut":         "Kókusz szedése",
    "Pick-dragonfruit":     "Sárkánygyümölcs szedése",
    "Pick-from":            "Szedés innen",
    "Pick-fruit":           "Gyümölcs szedése",
    "Pick-leaf":            "Levél szedése",
    "Pick-lock":            "Zárfeltörés",
    "Pick-lots":            "Sok szedése",
    "Pick-orange":          "Narancs szedése",
    "Pick-pineapple":       "Ananász szedése",
    "Pick-pocket":          "Zsebelés",
    "Pick-spine":           "Tüske szedése",
    "Picklock":             "Zárfeltörés",
    "Pickpocket":           "Zsebelés",
    "Steal":                "Lopás",
    "Steal from":           "Lopás innen",
    "Steal-From":           "Lopás innen",
    "Steal-from":           "Lopás innen",
    "Steal-cowbell":        "Kolomp ellopása",
    "Trap":                 "Csapda",
    "Set-trap":             "Csapda felállítása",
    "Catch":                "Fogás",
    "Net":                  "Háló",
    "Harpoon":              "Szigonyozás",
    "Cage":                 "Ketreccsapda",
    "Bait":                 "Csali",
    "Big Net":              "Nagy háló",
    "Small Net":            "Kis háló",
    "Pan":                  "Mosás",
    "Prospect":             "Felderítés",
    "Excavate":             "Ásatás",
    "Dig":                  "Ásás",
    "Dig-below":            "Alásás",
    "Dig-up":               "Kiásás",
    "Refine":               "Finomítás",
    "Clean":                "Tisztítás",
    "Cleanse":              "Megtisztítás",
    "Enchant":              "Varázslat",
    "Imbue":                "Feltöltés",
    "Recharge-jewellery":   "Ékszer feltöltése",
    "Recharge-whistle":     "Síp feltöltése",
    "Grind":                "Őrlés",
    "Chip":                 "Hasogatás",
    "Chisel":               "Faragás",
    "Carve-pumpkin":        "Tök faragása",
    "Churn":                "Köpülés",

    # ── Interaction ───────────────────────────────────────────────────────────
    "Search":               "Keresés",
    "Search for traps":     "Csapdák keresése",
    "Search-for-traps":     "Csapdák keresése",
    "Inspect":              "Vizsgálat",
    "Investigate":          "Vizsgálat",
    "Observe":              "Megfigyelés",
    "Study":                "Tanulmányozás",
    "Check":                "Ellenőrzés",
    "Check Kudos":          "Kudos ellenőrzése",
    "Check Scores":         "Pontszám ellenőrzése",
    "Check count":          "Szám ellenőrzése",
    "Check for Snakes":     "Kígyók keresése",
    "Check-Approval":       "Jóváhagyás ellenőrzése",
    "Check-Count":          "Szám ellenőrzése",
    "Check-Faith":          "Hit ellenőrzése",
    "Check-Fee":            "Díj ellenőrzése",
    "Check-ammo":           "Lőszer ellenőrzése",
    "Check-costume":        "Jelmez ellenőrzése",
    "Check-gates":          "Kapuk ellenőrzése",
    "Check-health":         "Egészség ellenőrzése",
    "Check-on":             "Ellenőrzés",
    "Check-permissions":    "Engedélyek ellenőrzése",
    "Check-pets":           "Állatok ellenőrzése",
    "Check-statistics (Global)":   "Statisztikák (Globális)",
    "Check-statistics (Personal)": "Statisztikák (Személyes)",
    "Check-times":          "Idők ellenőrzése",
    "Look":                 "Nézés",
    "Look East":            "Keletre nézés",
    "Look North":           "Északra nézés",
    "Look South":           "Délre nézés",
    "Look West":            "Nyugatra nézés",
    "Look at":              "Megnézés",
    "Look in":              "Benézés",
    "Look out":             "Kitekintés",
    "Look-at":              "Megnézés",
    "Look-in":              "Benézés",
    "Look-in-all":          "Mindenbe benézés",
    "Look-inside":          "Benézés",
    "Look-into":            "Benézés",
    "Look-over":            "Átnézés",
    "Look-through":         "Átnézés",
    "Look-under":           "Alanézés",
    "Look-up":              "Felkeresés",
    "Lookup":               "Keresés",
    "Peek":                 "Kukucskálás",
    "Peek (normal)":        "Kukucskálás (normál)",
    "Peer-into":            "Benézés",
    "Peer-through":         "Átnézés",
    "Watch":                "Figyelés",
    "Watch-shouting":       "Kiabálás figyelése",
    "Listen":               "Hallgatás",
    "Listen-at":            "Hallgatózás",
    "Listen-to":            "Hallgatás",
    "Count":                "Számlálás",
    "Count-plunder":        "Zsákmány számlálása",
    "Age":                  "Korbecslés",
    "Sense":                "Érzékelés",

    # ── UI / menu actions ─────────────────────────────────────────────────────
    "Cancel":               "Mégsem",
    "Continue":             "Folytatás",
    "Confirm":              "Megerősítés",
    "Accept":               "Elfogadás",
    "Decline":              "Visszautasítás",
    "Select":               "Kiválasztás",
    "Choose":               "Választás",
    "Choose spell":         "Varázslat választása",
    "Toggle":               "Váltás",
    "Toggle Accept Aid":    "Segítség elfogadásának váltása",
    "Toggle Counter":       "Számláló váltása",
    "Toggle Fossils":       "Fosszíliák váltása",
    "Toggle K/D":           "K/D váltása",
    "Toggle Run":           "Futás váltása",
    "Toggle XP":            "XP váltása",
    "Toggle skull prevention": "Koponya-védelem váltása",
    "Toggle unlock message":   "Feloldás üzenet váltása",
    "Toggle warning":       "Figyelmeztetés váltása",
    "Toggle warnings":      "Figyelmeztetések váltása",
    "Toggle-minerals":      "Ásványok váltása",
    "Toggle-talisman":      "Talizmán váltása",
    "Toggle-vials":         "Üvegcsék váltása",
    "Toggle-warning":       "Figyelmeztetés váltása",
    "Enable prayer filtering":    "Ima szűrés engedélyezése",
    "Enable prayer reordering":   "Ima átrendezés engedélyezése",
    "Enable spell filtering":     "Varázslat szűrés engedélyezése",
    "Enable spell reordering":    "Varázslat átrendezés engedélyezése",
    "Enable warning":       "Figyelmeztetés engedélyezése",
    "Disable prayer filtering":   "Ima szűrés letiltása",
    "Disable prayer reordering":  "Ima átrendezés letiltása",
    "Disable spell filtering":    "Varázslat szűrés letiltása",
    "Disable spell reordering":   "Varázslat átrendezés letiltása",
    "Disable warning":      "Figyelmeztetés letiltása",
    "Show":                 "Megjelenítés",
    "Hide":                 "Elrejtés",
    "Display":              "Megjelenítés",
    "View":                 "Megtekintés",
    "View Archive":         "Archívum megtekintése",
    "View Channel":         "Csatorna megtekintése",
    "View Friends List":    "Baráti lista megtekintése",
    "View History":         "Előzmények megtekintése",
    "View House Options":   "Házbeállítások megtekintése",
    "View Ignore List":     "Tiltólista megtekintése",
    "View Inbox":           "Beérkező megtekintése",
    "View Laps":            "Körök megtekintése",
    "View Newspost":        "Hír megtekintése",
    "View Poll":            "Szavazás megtekintése",
    "View Stats":           "Statisztikák megtekintése",
    "View another clan":    "Másik klán megtekintése",
    "View equipment stats": "Felszerelés statisztikái",
    "View guide prices":    "Irányárak megtekintése",
    "View items kept on death": "Halálon megtartott tárgyak",
    "View-game":            "Játék megtekintése",
    "View-glory":           "Dicsőség megtekintése",
    "View-stats":           "Statisztikák megtekintése",
    "View-trophies":        "Trófeák megtekintése",
    "Settings":             "Beállítások",
    "All Settings":         "Összes beállítás",
    "Configuration":        "Konfiguráció",
    "Configure":            "Beállítás",
    "Configure filter":     "Szűrő beállítása",
    "Preferences":          "Beállítások",
    "Controls":             "Irányítás",
    "Audio":                "Hang",
    "Animation":            "Animáció",
    "Display":              "Megjelenítés",
    "Visual-effects":       "Vizuális effektek",
    "Fullscreen <colNum0>World Map</col>": "Teljes képernyő <colNum0>Világtérkép</col>",
    "Floating <colNum0>World Map</col>":   "Lebegő <colNum0>Világtérkép</col>",
    "Export":               "Exportálás",
    "Import":               "Importálás",
    "Reset":                "Visszaállítás",
    "Reset-room":           "Szoba visszaállítása",
    "Reset-time":           "Idő visszaállítása",
    "Reset-wave":           "Hullám visszaállítása",
    "Restore Default Zoom": "Alapértelmezett nagyítás visszaállítása",
    "Logout":               "Kijelentkezés",
    "Setup your autochat":  "Automatikus chat beállítása",
    "Filter public chat":   "Nyilvános chat szűrése",
    "Clear history":        "Előzmények törlése",
    "Delete":               "Törlés",

    # ── Chat / social ─────────────────────────────────────────────────────────
    "Add Friend":           "Barát hozzáadása",
    "Add friend":           "Barát hozzáadása",
    "Add Name":             "Név hozzáadása",
    "Add Note":             "Megjegyzés hozzáadása",
    "Add ignore":           "Tiltólistára adás",
    "Delete Friend":        "Barát törlése",
    "Delete Name":          "Név törlése",
    "Remove friend":        "Barát törlése",
    "Remove ignore <!PLAYER_NAME0>": "Tiltólistáról törlés <!PLAYER_NAME0>",
    "Remove friend <!PLAYER_NAME0>": "Barát törlése <!PLAYER_NAME0>",
    "Add friend <!PLAYER_NAME0>":    "Barát hozzáadása <!PLAYER_NAME0>",
    "Add ignore <!PLAYER_NAME0>":    "Tiltólistára adás <!PLAYER_NAME0>",
    "Report":               "Jelentés",
    "Report abuse":         "Visszaélés jelentése",
    "Report game bug":      "Játékbug jelentése",
    "Message":              "Üzenet",
    "Chat-channel":         "Chat csatorna",
    "Channel":              "Csatorna",
    "Private":              "Privát",
    "Shared":               "Megosztott",
    "Commune":              "Kapcsolat",
    "Join Castle Wars":     "Csatlakozás: Castle Wars",
    "Expel Guests":         "Vendégek elküldése",
    "Community":            "Közösség",
    "Friends List":         "Baráti lista",
    "Grouping":             "Csoportosítás",
    "Your Clan":            "Saját klánod",
    "Ironman Group":        "Ironman csoport",
    "Show notifications":   "Értesítések megjelenítése",
    "Hide notifications":   "Értesítések elrejtése",
    "Warnings":             "Figyelmeztetések",
    "History":              "Előzmények",

    # ── Chat filter options ───────────────────────────────────────────────────
    "<colNum0>Channel:</col> Clear history":  "<colNum0>Csatorna:</col> Előzmények törlése",
    "<colNum0>Channel:</col> Show all":       "<colNum0>Csatorna:</col> Összes megjelenítése",
    "<colNum0>Channel:</col> Show friends":   "<colNum0>Csatorna:</col> Barátok megjelenítése",
    "<colNum0>Channel:</col> Show none":      "<colNum0>Csatorna:</col> Semmi sem látható",
    "<colNum0>Clan:</col> Clear history":     "<colNum0>Klán:</col> Előzmények törlése",
    "<colNum0>Clan:</col> Show all":          "<colNum0>Klán:</col> Összes megjelenítése",
    "<colNum0>Clan:</col> Show friends":      "<colNum0>Klán:</col> Barátok megjelenítése",
    "<colNum0>Clan:</col> Show none":         "<colNum0>Klán:</col> Semmi sem látható",
    "<colNum0>Game:</col> Clear history":     "<colNum0>Játék:</col> Előzmények törlése",
    "<colNum0>Game:</col> Filter":            "<colNum0>Játék:</col> Szűrő",
    "<colNum0>Group:</col> Clear history":    "<colNum0>Csoport:</col> Előzmények törlése",
    "<colNum0>Group:</col> Show all":         "<colNum0>Csoport:</col> Összes megjelenítése",
    "<colNum0>Group:</col> Show friends":     "<colNum0>Csoport:</col> Barátok megjelenítése",
    "<colNum0>Group:</col> Show none":        "<colNum0>Csoport:</col> Semmi sem látható",
    "<colNum0>Private:</col> Clear history":  "<colNum0>Privát:</col> Előzmények törlése",
    "<colNum0>Private:</col> Show all":       "<colNum0>Privát:</col> Összes megjelenítése",
    "<colNum0>Private:</col> Show friends":   "<colNum0>Privát:</col> Barátok megjelenítése",
    "<colNum0>Private:</col> Show none":      "<colNum0>Privát:</col> Semmi sem látható",
    "<colNum0>Public:</col> Clear history":   "<colNum0>Nyilvános:</col> Előzmények törlése",
    "<colNum0>Public:</col> Hide":            "<colNum0>Nyilvános:</col> Elrejtés",
    "<colNum0>Public:</col> Show autochat":   "<colNum0>Nyilvános:</col> Autochat megjelenítése",
    "<colNum0>Public:</col> Show friends":    "<colNum0>Nyilvános:</col> Barátok megjelenítése",
    "<colNum0>Public:</col> Show none":       "<colNum0>Nyilvános:</col> Semmi sem látható",
    "<colNum0>Public:</col> Show standard":   "<colNum0>Nyilvános:</col> Alapértelmezett megjelenítése",
    "<colNum0>Set chat mode:</col> Channel (/@f)":    "<colNum0>Chat mód:</col> Csatorna (/@f)",
    "<colNum0>Set chat mode:</col> Clan (/@c)":       "<colNum0>Chat mód:</col> Klán (/@c)",
    "<colNum0>Set chat mode:</col> Group (/@g)":      "<colNum0>Chat mód:</col> Csoport (/@g)",
    "<colNum0>Set chat mode:</col> Guest Clan (/@gc)":"<colNum0>Chat mód:</col> Vendég klán (/@gc)",
    "<colNum0>Set chat mode:</col> Public (/@p)":     "<colNum0>Chat mód:</col> Nyilvános (/@p)",
    "<colNum0>Trade:</col> Clear history":    "<colNum0>Kereskedés:</col> Előzmények törlése",
    "<colNum0>Trade:</col> Show all":         "<colNum0>Kereskedés:</col> Összes megjelenítése",
    "<colNum0>Trade:</col> Show friends":     "<colNum0>Kereskedés:</col> Barátok megjelenítése",
    "<colNum0>Trade:</col> Show none":        "<colNum0>Kereskedés:</col> Semmi sem látható",

    # ── Skills / menus ────────────────────────────────────────────────────────
    "Skills":               "Készségek",
    "Stats":                "Statisztikák",
    "Status":               "Állapot",
    "Character Summary":    "Karakter összefoglaló",
    "Equipment":            "Felszerelés",
    "Worn Equipment":       "Viselt felszerelés",
    "Inventory":            "Leltár",
    "Prayer":               "Ima",
    "Pray":                 "Ima",
    "Pray-at":              "Imádkozás itt",
    "Spellbook":            "Varázskönyv",
    "Magic":                "Mágia",
    "Emotes":               "Emóciók",
    "Emote":                "Emóció",
    "Music Player":         "Zenei lejátszó",
    "Clan":                 "Klán",
    "Quest List":           "Küldetéslista",
    "Achievement Diaries":  "Teljesítmény naplók",
    "Collection Log":       "Gyűjtési napló",
    "Collection Overview":  "Gyűjtési áttekintő",
    "Tasks":                "Feladatok",
    "Task":                 "Feladat",
    "Bosses":               "Főellenségek",
    "Assignment":           "Megbízatás",
    "Armour":               "Páncél",
    "Ammo":                 "Lőszer",
    "Bars":                 "Rudak",
    "Staves":               "Varázspálcák",
    "Gauntlets":            "Kesztyűk",
    "Potions":              "Főzetek",
    "Seeds":                "Magvak",
    "Jars":                 "Üvegek",
    "Items":                "Tárgyak",
    "Sets":                 "Szettek",
    "Dyes":                 "Festékek",
    "Trophies":             "Trófeák",
    "Perks":                "Bónuszok",
    "Rewards":              "Jutalmak",
    "Mines":                "Bányák",
    "Area":                 "Terület",
    "Nets":                 "Hálók",
    "Locks":                "Zárak",
    "Account":              "Fiók",
    "Account Management":   "Fiókkezelés",
    "Name Changer":         "Névváltás",
    "Scoreboard":           "Rangsor",
    "World Switcher":       "Világ váltó",
    "Home":                 "Főoldal",
    "Wiki":                 "Wiki",
    "Useful Links":         "Hasznos linkek",
    "Tutorial":             "Oktatóanyag",
    "Manual":               "Kézikönyv",
    "Devices":              "Eszközök",
    "Other-services":       "Egyéb szolgáltatások",
    "Prices":               "Árak",
    "Value":                "Érték",
    "Level":                "Szint",
    "Rank":                 "Rang",
    "Training":             "Edzés",
    "Statistics":           "Statisztikák",
    "Overview":             "Áttekintő",
    "Story":                "Történet",
    "Random":               "Véletlenszerű",
    "Outside":              "Kint",

    # ── Building / Construction ───────────────────────────────────────────────
    "Build":                "Építés",
    "Build mode":           "Építési mód",
    "Build on":             "Építés ide",
    "Build-barricade":      "Torlasz építése",
    "Build-in":             "Beépítés",
    "Demolish":             "Lebontás",
    "Remove-room":          "Szoba eltávolítása",
    "Redecorate":           "Újradekorálás",
    "Construct":            "Megépítés",
    "Assemble":             "Összeszerkesztés",
    "Dismantle":            "Szétszerelés",
    "Repair":               "Javítás",
    "Repairs":              "Javítások",
    "Commission":           "Megbízás",
    "Cellar":               "Pince",
    "Bottom-Floor":         "Alsó szint",
    "Bottom-floor":         "Alsó szint",
    "Top-Floor":            "Felső szint",
    "Top-floor":            "Felső szint",
    "Call Servant":         "Szolga hívása",
    "Upgrade":              "Fejlesztés",
    "Reinforce":            "Megerősítés",

    # ── Miscellaneous actions ─────────────────────────────────────────────────
    "Activate":             "Aktiválás",
    "Deactivate":           "Deaktiválás",
    "Absorb":               "Felszívás",
    "Attract":              "Vonzás",
    "Animate":              "Animálás",
    "Adjust":               "Beállítás",
    "Admire":               "Csodálat",
    "Attach":               "Rögzítés",
    "Attach-rope":          "Kötél rögzítése",
    "Add to":               "Hozzáadás",
    "Add to canvas":        "Vászonra adás",
    "Add-House":            "Ház hozzáadása",
    "Add-bottom":           "Alap hozzáadása",
    "Add-mulch":            "Mulcs hozzáadása",
    "Adjust Area Sound Volume":    "Területi hangerő beállítása",
    "Adjust Brightness":           "Fényerő beállítása",
    "Adjust Music Volume":         "Zenei hangerő beállítása",
    "Adjust Sound Effect Volume":  "Hangeffekt hangerő beállítása",
    "Add finds":            "Leletek hozzáadása",
    "Align":                "Igazítás",
    "Align-net":            "Háló igazítása",
    "Apply":                "Alkalmazás",
    "Awaken":               "Felébresztés",
    "Balance":              "Egyensúlyozás",
    "Balance-across":       "Egyensúlyozás átkeléskor",
    "Bask":                 "Sütkérezés",
    "Begin":                "Kezdés",
    "Bend":                 "Hajlítás",
    "Big-push":             "Nagy lökés",
    "Big-search":           "Nagy keresés",
    "Blaze":                "Lángolás",
    "Bless":                "Megáldás",
    "Break":                "Törés",
    "Burst":                "Robbantás",
    "Buy-crystals":         "Kristályok vásárlása",
    "Buy-food":             "Étel vásárlása",
    "Buy-items":            "Tárgyak vásárlása",
    "Buy-pass":             "Bérlet vásárlása",
    "Buy-plank":            "Deszka vásárlása",
    "Buy-sphere":           "Gömb vásárlása",
    "Call follower":        "Követő hívása",
    "Call-Over":            "Odahívás",
    "Capture":              "Elfogás",
    "Charm Snake":          "Kígyó bűvölése",
    "Charter":              "Bérlet",
    "Chase":                "Üldözés",
    "Clamber":              "Kúszás",
    "Claim Pet Rock":       "Háziállat kő átvétele",
    "Claim Sand":           "Homok átvétele",
    "Claim-Shield":         "Pajzs átvétele",
    "Claim-Tokens":         "Zsetonok átvétele",
    "Claim-arrows":         "Nyilak átvétele",
    "Claim-cape":           "Köpeny átvétele",
    "Claim-log-rewards":    "Napló jutalmak átvétele",
    "Claim-runes":          "Rúnák átvétele",
    "Claim-slime":          "Nyálka átvétele",
    "Claim-staves":         "Pálcák átvétele",
    "Claim-trophies":       "Trófeák átvétele",
    "Cleanse":              "Megtisztítás",
    "Clip":                 "Klip",
    "Coffer":               "Széf",
    "Collapse":             "Összeomlás",
    "Collect":              "Gyűjtés",
    "Collect-from":         "Gyűjtés innen",
    "Collect-items":        "Tárgyak gyűjtése",
    "Collect-reward":       "Jutalom gyűjtése",
    "Complete":             "Befejezés",
    "Concentrate-potion":   "Főzet sűrítése",
    "Confront":             "Szembesítés",
    "Control":              "Irányítás",
    "Convert":              "Átalakítás",
    "Convert-shards":       "Cserepek átalakítása",
    "Cool-preform":         "Lehűtés",
    "Crack":                "Feltörés",
    "Crystalise-potion":    "Főzet kristályosítása",
    "Cure":                 "Gyógyítás",
    "DPS":                  "DPS",
    "Decapitate":           "Lefejezés",
    "Deflect":              "Kitérés",
    "Deposit buckets":      "Vedrek letétele",
    "Deposit-box":          "Letéti doboz",
    "Deposit-eggs":         "Tojások letétele",
    "Deposit-items":        "Tárgyak letétele",
    "Deposit-pickaxe":      "Csákány letétele",
    "Deposit-runes":        "Rúnák letétele",
    "Destroy":              "Megsemmisítés",
    "Detach":               "Leválasztás",
    "Dig-below":            "Alásás",
    "Dig-up":               "Kiásás",
    "Direct-portal":        "Portál irányítása",
    "Disarm":               "Lefegyverzés",
    "Dismiss":              "Elküldés",
    "Dispel":               "Feloszlatás",
    "Distract":             "Elterelés",
    "Disturb":              "Zavarás",
    "Dondakan's Rock":      "Dondakan sziklája",
    "Douse":                "Eloltás",
    "Drain":                "Leszívás",
    "Dream":                "Álmodozás",
    "Dump":                 "Kirakás",
    "Dunk":                 "Bemerítés",
    "Dunk-preform":         "Előgyártmány bemerítése",
    "Eat-from":             "Evés innen",
    "Empty":                "Kiürítés",
    "Empty-Out":            "Kiürítés",
    "Enchant":              "Varázslat",
    "Enter-cloud":          "Felhőbe lépés",
    "Entertain":            "Szórakoztatás",
    "Escort":               "Kíséret",
    "Evade":                "Kitérés",
    "Evade-event":          "Esemény elkerülése",
    "Escape":               "Menekülés",
    "Escape-event":         "Eseményből menekülés",
    "Exchange":             "Csere",
    "Exchange fire cape":   "Tűzköpeny cseréje",
    "Excavate":             "Ásatás",
    "Extinguish":           "Eloltás",
    "Feed":                 "Etetés",
    "Feel":                 "Érintés",
    "Fend":                 "Védekezés",
    "Fill-bucket":          "Vödör feltöltése",
    "Fill-from":            "Feltöltés innen",
    "Fill-jug":             "Korsó feltöltése",
    "Flare":                "Jelzőfáklya",
    "Float Canoe":          "Kenu lebegtetése",
    "Float Log":            "Rönk lebegtetése",
    "Flush":                "Átöblítés",
    "Fly":                  "Repülés",
    "Focus":                "Fókuszálás",
    "Force":                "Kényszerítés",
    "Fuel":                 "Üzemanyagozás",
    "Fulfil-order":         "Megrendelés teljesítése",
    "Fur Clothing":         "Prém ruházat",
    "Fur-clothing":         "Prém ruházat",
    "Gaze-into":            "Benézés",
    "Gear":                 "Felszerelés",
    "Get bird":             "Madár fogása",
    "Get in":               "Beszállás",
    "Get job (easy)":       "Munka kapása (könnyű)",
    "Get job (hard)":       "Munka kapása (nehéz)",
    "Get-Spikes":           "Tüskék szerzése",
    "Get-down":             "Lemenetel",
    "Get-log":              "Rönk szerzése",
    "Get-rewards":          "Jutalmak szerzése",
    "Give-Stick":           "Bot adása",
    "Give-Sword":           "Kard adása",
    "Glade":                "Tisztás",
    "Glider":               "Sárkányrepülő",
    "Grab":                 "Megragadás",
    "Grab-feather":         "Toll megragadása",
    "Guess-letter":         "Betű tippelése",
    "Hack":                 "Vágás",
    "Haircut":              "Hajvágás",
    "Hammer":               "Kalapácsolás",
    "Hand-in":              "Átadás",
    "Hang-over":            "Átlógatás",
    "Harvest":              "Aratás",
    "Heart":                "Szív",
    "Heat-preform":         "Előgyártmány melegítése",
    "Holiday-items":        "Ünnepi tárgyak",
    "Homogenise-potion":    "Főzet homogenizálása",
    "Honour":               "Tisztelet",
    "Hoop":                 "Karika",
    "Hop-to":               "Ugrás ide",
    "Hurdle":               "Akadályozás",
    "Imbue":                "Feltöltés",
    "Impale":               "Felnyársal",
    "Inject":               "Befecskendezés",
    "Interact":             "Interakció",
    "Join":                 "Csatlakozás",
    "Join-Crew":            "Csapat csatlakozás",
    "Join-Team":            "Csapat csatlakozás",
    "Knock-Out":            "Kiütés",
    "Knock-at":             "Kopogás",
    "Lap-count":            "Körszámláló",
    "Last-tier contract":   "Utolsó szintű szerződés",
    "League-firsts":        "Liga elsők",
    "League-rankings":      "Liga rangsor",
    "League-statistics":    "Liga statisztikák",
    "Learn More":           "Tudj meg többet",
    "Light":                "Meggyújtás",
    "Load":                 "Betöltés",
    "Lock":                 "Zárás",
    "Locking":              "Zárás",
    "Lockpick":             "Zárfeltörés",
    "Log-storage":          "Rönktár",
    "Loop":                 "Hurok",
    "Loot":                 "Zsákmányolás",
    "Lure":                 "Csalivetés",
    "Lunge":                "Szúrás",
    "Make-cuppa":           "Teafőzés",
    "Make-helmet":          "Sisak készítése",
    "Make-raft":            "Tutaj készítése",
    "Make unfinished potion(s)": "Befejezetlen főzet(ek) készítése",
    "Makeover":             "Átalakítás",
    "Manoeuvre-past":       "Elkerülés",
    "Mark":                 "Megjelölés",
    "Melt":                 "Olvasztás",
    "Metamorph":            "Átalakulás",
    "Metamorphosis":        "Metamorfózis",
    "Milk":                 "Fejés",
    "Navigate":             "Navigálás",
    "New-maze":             "Új labirintus",
    "Off":                  "Ki",
    "On":                   "Be",
    "Offer-fish":           "Hal felajánlása",
    "Operate":              "Kezelés",
    "Paddle Canoe":         "Kenu evezése",
    "Paddle Log":           "Rönk evezése",
    "Pass-to":              "Átadás",
    "Pedal":                "Pedálozás",
    "Perform":              "Előadás",
    "Pet":                  "Simogatás",
    "Plant-evidence":       "Bizonyíték elhelyezése",
    "Plant-orb":            "Gömb elhelyezése",
    "Play-quietly":         "Halk játék",
    "Pluck":                "Tépés",
    "Poke":                 "Bökés",
    "Pop":                  "Kipukkasztás",
    "Pound":                "Zúzás",
    "Pour":                 "Öntés",
    "Power-up":             "Feltöltés",
    "Preen":                "Tollászkodás",
    "Prepare-fish":         "Hal előkészítése",
    "Press":                "Megnyomás",
    "Proceed":              "Folytatás",
    "Prod":                 "Bökés",
    "Pull-down":            "Lehúzás",
    "Pull-spade":           "Ásó húzása",
    "Purchase Amulet":      "Amulett vásárlása",
    "Push-against":         "Nekitolás",
    "Push-through":         "Áttolás",
    "Push-up":              "Feltolás",
    "Put-inside":           "Betétel",
    "Put-ore-on":           "Érc feltétele",
    "Quench":               "Csillapítás",
    "Quench-preform":       "Előgyártmány hűtése",
    "Quick Pass":           "Gyors áthaladás",
    "Quick-Board":          "Gyors felszállás",
    "Quick-Enter":          "Gyors belépés",
    "Quick-Exit":           "Gyors kilépés",
    "Quick-Pass":           "Gyors áthaladás",
    "Quick-Pay(100)":       "Gyors fizetés (100)",
    "Quick-Travel":         "Gyors utazás",
    "Quick-Use":            "Gyors használat",
    "Quick-board":          "Gyors felszállás",
    "Quick-climb":          "Gyors mászás",
    "Quick-enter":          "Gyors belépés",
    "Quick-escape":         "Gyors menekülés",
    "Quick-exit":           "Gyors kilépés",
    "Quick-falcon":         "Gyors sólyom",
    "Quick-leave":          "Gyors távozás",
    "Quick-lock":           "Gyors zárás",
    "Quick-open":           "Gyors megnyitás",
    "Quick-pass":           "Gyors áthaladás",
    "Quick-slide":          "Gyors csúszás",
    "Quick-start":          "Gyors indítás",
    "Quick-travel":         "Gyors utazás",
    "Quick-use":            "Gyors használat",
    "Quick-withdraw":       "Gyors kivétel",
    "Re-light":             "Újrafelgyújtás",
    "Reach":                "Elérés",
    "Read journal:":        "Napló olvasása:",
    "Reanimate":            "Újraélesztés",
    "Reap":                 "Aratás",
    "Rebalance":            "Újraelosztás",
    "Redeem":               "Beváltás",
    "Redeem-code":          "Kód beváltása",
    "Refuel":               "Feltankolás",
    "Reinvigorate":         "Megelevenítés",
    "Release-bees":         "Méhek engedése",
    "Relocate":             "Áthelyezés",
    "Reminisce":            "Visszaemlékezés",
    "Remove PvP Protection":        "PvP védelem eltávolítása",
    "Remove board advert":          "Tábla hirdetés eltávolítása",
    "Remove-Bone":          "Csont eltávolítása",
    "Remove-Pot":           "Fazék eltávolítása",
    "Remove-banner":        "Zászló eltávolítása",
    "Remove-coal":          "Szén eltávolítása",
    "Remove-decorations":   "Díszítések eltávolítása",
    "Remove-outfit":        "Öltözet eltávolítása",
    "Remove-trophy":        "Trófea eltávolítása",
    "Request-supplies":     "Készletek kérése",
    "Resign":               "Lemondás",
    "Rest":                 "Pihenés",
    "Resurrect":            "Feltámasztás",
    "Retrieve":             "Visszaszerzés",
    "Retrieve-egg":         "Tojás visszaszerzése",
    "Return":               "Visszatérés",
    "Return-Home":          "Visszatérés otthonra",
    "Return-to-Burgh":      "Visszatérés Burghba",
    "Return-to-Paterdomus": "Visszatérés Paterdomusba",
    "Reveal":               "Felfedés",
    "Revert":               "Visszaállítás",
    "Ride":                 "Lovaglás",
    "Ring":                 "Csörgés",
    "Ring-Zanaris":         "Zanaris csörgése",
    "Ring-bell":            "Harang csörgése",
    "Ring-configure":       "Gyűrű beállítása",
    "Roll":                 "Gördülés",
    "Rotate":               "Forgatás",
    "Rotate-anticlockwise": "Forgás az óramutató járásával ellentétesen",
    "Rotate-clockwise":     "Forgás az óramutató járásával",
    "Rummage":              "Turkálás",
    "Rumour":               "Pletyka",
    "Rumour-settings":      "Pletyka beállítások",
    "Rustle":               "Zizegtetés",
    "Sabotage":             "Szabotázs",
    "Sacrifice":            "Feláldozás",
    "Sacrifice-fragments":  "Töredékek feláldozása",
    "Sand":                 "Homokozás",
    "Say-name":             "Név kimondása",
    "Scale":                "Mérés",
    "Scare":                "Megijesztés",
    "Scare-away":           "Elriasztás",
    "Scorch":               "Megperzselés",
    "Scry":                 "Jóslás",
    "Send-parcel":          "Csomag küldése",
    "Set Destination":      "Célpont beállítása",
    "Set destination":      "Célpont beállítása",
    "Set up":               "Beállítás",
    "Set-difficulty":       "Nehézség beállítása",
    "Set-up":               "Beállítás",
    "Setup":                "Beállítás",
    "Sew":                  "Varrás",
    "Shake":                "Rázás",
    "Shape-Canoe":          "Kenu alakítása",
    "Shave":                "Borotválás",
    "Shear":                "Nyírás",
    "Shoo":                 "Hessegetés",
    "Shoo-away":            "Elzavarás",
    "Shout-over":           "Átkiabálás",
    "Shout-to":             "Odakiabálás",
    "Show-Goal":            "Cél megmutatása",
    "Show on map:":         "Megmutatás a térképen:",
    "Shut":                 "Bezárás",
    "Sing":                 "Éneklés",
    "Sing-crystal":         "Kristály éneklése",
    "Sit-On":               "Ráülés",
    "Sit-on":               "Ráülés",
    "Skin":                 "Bőrözés",
    "Skull":                "Koponya",
    "Sleep-in":             "Alvás benne",
    "Smash-ice":            "Jég szétzúzása",
    "Smash-to-bits":        "Darabokra zúzás",
    "Smoke":                "Füstölés",
    "Sober-Up":             "Kijózanítás",
    "Solo-start":           "Egyedüli indítás",
    "Spectate":             "Nézőként részvétel",
    "Spike":                "Tüskézés",
    "Spin-globe":           "Glóbusz forgatása",
    "Stamp-out":            "Kinyomás",
    "Stand-on":             "Ráállás",
    "Start Helper":         "Segítő indítása",
    "Start Quest Helper":   "Küldetés segítő indítása",
    "Start-minigame":       "Minijáték indítása",
    "Start-wave":           "Hullám indítása",
    "Step-into":            "Belépés",
    "Step-off":             "Lelépés",
    "Step-on":              "Rálépés",
    "Step-over":            "Átlépés",
    "Stock-Up":             "Feltöltés",
    "Store-plunder":        "Zsákmány tárolása",
    "Store-preform":        "Előgyártmány tárolása",
    "Strike":               "Ütés",
    "Stroke":               "Simogatás",
    "Suck":                 "Szívás",
    "Supply":               "Ellátás",
    "Swap":                 "Csere",
    "Swap-options":         "Lehetőségek cseréje",
    "Switch":               "Váltás",
    "Switch tab":           "Fül váltása",
    "Switch world":         "Világ váltása",
    "Tackle":               "Megfogás",
    "Tag":                  "Megjelölés",
    "Take From":            "Vétel innen",
    "Take Rake":            "Gereblye felvétele",
    "Take Seed Dibber":     "Magvető felvétele",
    "Take Spade":           "Ásó felvétele",
    "Take anglerfish":      "Szögcsukahorgász hal felvétele",
    "Take down":            "Lebontás",
    "Take manta ray":       "Manta rája felvétele",
    "Take pages":           "Lapok felvétele",
    "Take tools":           "Eszközök felvétele",
    "Take treasure":        "Kincs felvétele",
    "Take-1":               "1 felvétele",
    "Take-10":              "10 felvétele",
    "Take-10 concoctions":  "10 főzet felvétele",
    "Take-5":               "5 felvétele",
    "Take-5 concoctions":   "5 főzet felvétele",
    "Take-Arrows":          "Nyilak felvétele",
    "Take-Beam":            "Gerenda felvétele",
    "Take-Coffin":          "Koporsó felvétele",
    "Take-Crackers":        "Keksz felvétele",
    "Take-Log":             "Rönk felvétele",
    "Take-Meat":            "Hús felvétele",
    "Take-Pulley-Beam":     "Csigasor gerenda felvétele",
    "Take-Rope":            "Kötél felvétele",
    "Take-Rum":             "Rum felvétele",
    "Take-Runes":           "Rúnák felvétele",
    "Take-Tofu":            "Tofu felvétele",
    "Take-Tool":            "Eszköz felvétele",
    "Take-Vial":            "Üvegcse felvétele",
    "Take-Worms":           "Férgek felvétele",
    "Take-X":               "X felvétele",
    "Take-axe":             "Fejsze felvétele",
    "Take-beer":            "Sör felvétele",
    "Take-boat":            "Csónak felvétele",
    "Take-bowl":            "Tál felvétele",
    "Take-candy":           "Cukorka felvétele",
    "Take-chisel":          "Véső felvétele",
    "Take-concoction":      "Főzet felvétele",
    "Take-cutting":         "Dugvány felvétele",
    "Take-flyer":           "Szórólap felvétele",
    "Take-from":            "Felvétel innen",
    "Take-from Fishing":    "Felvétel (Halászat)",
    "Take-from Herblore":   "Felvétel (Gyógynövény)",
    "Take-from Hunting":    "Felvétel (Vadászat)",
    "Take-hammer":          "Kalapács felvétele",
    "Take-kettle":          "Vízforraló felvétele",
    "Take-knife":           "Kés felvétele",
    "Take-log":             "Rönk felvétele",
    "Take-lure":            "Csali felvétele",
    "Take-many":            "Sok felvétele",
    "Take-net":             "Háló felvétele",
    "Take-pickaxe":         "Csákány felvétele",
    "Take-powder":          "Por felvétele",
    "Take-preform":         "Előgyártmány felvétele",
    "Take-remains":         "Maradványok felvétele",
    "Take-rock":            "Kő felvétele",
    "Take-seed":            "Mag felvétele",
    "Take-sigil":           "Pecsét felvétele",
    "Take-supplies":        "Készletek felvétele",
    "Take-tinderbox":       "Tűzszerszám felvétele",
    "Take-uniform":         "Egyenruha felvétele",
    "Tamper":               "Babrálás",
    "Tap":                  "Megérintés",
    "Tease":                "Ingerkedés",
    "Teeth-grip":           "Fogással megfogás",
    "Tend-to":              "Gondozás",
    "Tether":               "Kikötés",
    "Tie-rope":             "Kötél megkötése",
    "Touch":                "Megérintés",
    "Trade-Builders-Store": "Építők boltja",
    "Trade-Co-op":          "Szövetkezeti kereskedés",
    "Trade-Drinks":         "Italok kereskedése",
    "Trade-General-Store":  "Általános bolt",
    "Tread-softly":         "Halk léptek",
    "Tree":                 "Fa",
    "Trick-or-treat":       "Csokit vagy csalunk",
    "Trophies":             "Trófeák",
    "Turn":                 "Fordítás",
    "Turn-Off":             "Kikapcsolás",
    "Tuxedo-time":          "Frakkidő",
    "Unblock":              "Tiltás feloldása",
    "Unhide":               "Megjelenítés",
    "Unlock":               "Feloldás",
    "Unlock hint":          "Tipp feloldása",
    "Unmark":               "Jelölés törlése",
    "Unmute":               "Hang visszaállítása",
    "Untether":             "Kikötés megszüntetése",
    "Untie":                "Kibontás",
    "Use-Driftwood":        "Sodrófa használata",
    "Use-Lift":             "Lift használata",
    "Use-rod":              "Horgász bot használata",
    "Vault":                "Trezor",
    "Venerate":             "Tisztelet",
    "Vent":                 "Szellőzés",
    "Visit-Last":           "Utolsó látogatás",
    "Waterproof":           "Vízállóvá tétel",
    "Wind":                 "Feltekerés",
    "Wind-up":              "Felhúzás",
    "Work-at":              "Munka itt",
    "Worship":              "Imádat",
    "search":               "keresés",
    "talk":                 "megszólítás",
    "test":                 "teszt",

    # ── Skill guide views (keep skill names in English) ───────────────────────
    "View <colNum0>Agility</col> guide":      "Útmutató: <colNum0>Agility</col>",
    "View <colNum0>Attack</col> guide":       "Útmutató: <colNum0>Attack</col>",
    "View <colNum0>Construction</col> guide": "Útmutató: <colNum0>Construction</col>",
    "View <colNum0>Cooking</col> guide":      "Útmutató: <colNum0>Cooking</col>",
    "View <colNum0>Crafting</col> guide":     "Útmutató: <colNum0>Crafting</col>",
    "View <colNum0>Defence</col> guide":      "Útmutató: <colNum0>Defence</col>",
    "View <colNum0>Farming</col> guide":      "Útmutató: <colNum0>Farming</col>",
    "View <colNum0>Firemaking</col> guide":   "Útmutató: <colNum0>Firemaking</col>",
    "View <colNum0>Fishing</col> guide":      "Útmutató: <colNum0>Fishing</col>",
    "View <colNum0>Fletching</col> guide":    "Útmutató: <colNum0>Fletching</col>",
    "View <colNum0>Herblore</col> guide":     "Útmutató: <colNum0>Herblore</col>",
    "View <colNum0>Hitpoints</col> guide":    "Útmutató: <colNum0>Hitpoints</col>",
    "View <colNum0>Hunter</col> guide":       "Útmutató: <colNum0>Hunter</col>",
    "View <colNum0>Magic</col> guide":        "Útmutató: <colNum0>Magic</col>",
    "View <colNum0>Mining</col> guide":       "Útmutató: <colNum0>Mining</col>",
    "View <colNum0>Prayer</col> guide":       "Útmutató: <colNum0>Prayer</col>",
    "View <colNum0>Ranged</col> guide":       "Útmutató: <colNum0>Ranged</col>",
    "View <colNum0>Runecraft</col> guide":    "Útmutató: <colNum0>Runecraft</col>",
    "View <colNum0>Slayer</col> guide":       "Útmutató: <colNum0>Slayer</col>",
    "View <colNum0>Smithing</col> guide":     "Útmutató: <colNum0>Smithing</col>",
    "View <colNum0>Strength</col> guide":     "Útmutató: <colNum0>Strength</col>",
    "View <colNum0>Thieving</col> guide":     "Útmutató: <colNum0>Thieving</col>",
    "View <colNum0>Woodcutting</col> guide":  "Útmutató: <colNum0>Woodcutting</col>",

    # ── Journal opens / wikis (keep journal names in English) ─────────────────
    "Open <colNum0>Ardougne Journal</col>":           "Megnyitás: <colNum0>Ardougne napló</col>",
    "Open <colNum0>Desert Journal</col>":             "Megnyitás: <colNum0>Sivatag napló</col>",
    "Open <colNum0>Falador Journal</col>":            "Megnyitás: <colNum0>Falador napló</col>",
    "Open <colNum0>Fremennik Journal</col>":          "Megnyitás: <colNum0>Fremennik napló</col>",
    "Open <colNum0>Kandarin Journal</col>":           "Megnyitás: <colNum0>Kandarin napló</col>",
    "Open <colNum0>Karamja Journal</col>":            "Megnyitás: <colNum0>Karamja napló</col>",
    "Open <colNum0>Kourend & Kebos Journal</col>":    "Megnyitás: <colNum0>Kourend & Kebos napló</col>",
    "Open <colNum0>Lumbridge & Draynor Journal</col>":"Megnyitás: <colNum0>Lumbridge & Draynor napló</col>",
    "Open <colNum0>Morytania Journal</col>":          "Megnyitás: <colNum0>Morytania napló</col>",
    "Open <colNum0>Varrock Journal</col>":            "Megnyitás: <colNum0>Varrock napló</col>",
    "Open <colNum0>Western Provinces Journal</col>":  "Megnyitás: <colNum0>Nyugati tartományok napló</col>",
    "Open <colNum0>Wilderness Journal</col>":         "Megnyitás: <colNum0>Vadon napló</col>",
    "Open Activity Adviser":    "Tevékenység-tanácsadó megnyitása",
    "Open Adventure Paths":     "Kalandösvények megnyitása",
    "Open Bond Pouch":          "Bond erszény megnyitása",
    "Open Store":               "Bolt megnyitása",
    "Open subsection":          "Alfejezet megnyitása",
    "Open wiki guide:":         "Wiki útmutató megnyitása:",
    "Open wiki quick guide:":   "Wiki gyors útmutató megnyitása:",
    "Wiki <colNum0>Ardougne Journal</col>":           "Wiki: <colNum0>Ardougne napló</col>",
    "Wiki <colNum0>Desert Journal</col>":             "Wiki: <colNum0>Sivatag napló</col>",
    "Wiki <colNum0>Falador Journal</col>":            "Wiki: <colNum0>Falador napló</col>",
    "Wiki <colNum0>Fremennik Journal</col>":          "Wiki: <colNum0>Fremennik napló</col>",
    "Wiki <colNum0>Kandarin Journal</col>":           "Wiki: <colNum0>Kandarin napló</col>",
    "Wiki <colNum0>Karamja Journal</col>":            "Wiki: <colNum0>Karamja napló</col>",
    "Wiki <colNum0>Kourend & Kebos Journal</col>":    "Wiki: <colNum0>Kourend & Kebos napló</col>",
    "Wiki <colNum0>Lumbridge & Draynor Journal</col>":"Wiki: <colNum0>Lumbridge & Draynor napló</col>",
    "Wiki <colNum0>Morytania Journal</col>":          "Wiki: <colNum0>Morytania napló</col>",
    "Wiki <colNum0>Varrock Journal</col>":            "Wiki: <colNum0>Varrock napló</col>",
    "Wiki <colNum0>Western Provinces Journal</col>":  "Wiki: <colNum0>Nyugati tartományok napló</col>",
    "Wiki <colNum0>Wilderness Journal</col>":         "Wiki: <colNum0>Vadon napló</col>",

    # ── Channel region tags ────────────────────────────────────────────────────
    "Channel (Asgarnia)":       "Csatorna (Asgarnia)",
    "Channel (Fremennik)":      "Csatorna (Fremennik)",
    "Channel (Great Kourend)":  "Csatorna (Nagy Kourend)",
    "Channel (Kandarin)":       "Csatorna (Kandarin)",
    "Channel (Karamja)":        "Csatorna (Karamja)",
    "Channel (Kharidian Desert)": "Csatorna (Kharid sivatag)",
    "Channel (Misthalin)":      "Csatorna (Misthalin)",
    "Channel (Morytania)":      "Csatorna (Morytania)",
    "Channel (Tirannwn)":       "Csatorna (Tirannwn)",
    "Channel (Varlamore)":      "Csatorna (Varlamore)",
    "Channel (Wilderness)":     "Csatorna (Vadon)",

    # ── Charter ships (leave destinations in English) ─────────────────────────
    "Charter":                          "Bérelt hajó",
    "Charter-to Aldarin":               "Hajó bérlése: Aldarin",
    "Charter-to Brimhaven":             "Hajó bérlése: Brimhaven",
    "Charter-to Catherby":              "Hajó bérlése: Catherby",
    "Charter-to Civitas illa Fortis":   "Hajó bérlése: Civitas illa Fortis",
    "Charter-to Corsair Cove":          "Hajó bérlése: Corsair Cove",
    "Charter-to Land's End":            "Hajó bérlése: Land's End",
    "Charter-to Mos Le'Harmless":       "Hajó bérlése: Mos Le'Harmless",
    "Charter-to Musa Point":            "Hajó bérlése: Musa Point",
    "Charter-to Port Khazard":          "Hajó bérlése: Port Khazard",
    "Charter-to Port Phasmatys":        "Hajó bérlése: Port Phasmatys",
    "Charter-to Port Piscarilius":      "Hajó bérlése: Port Piscarilius",
    "Charter-to Port Sarim":            "Hajó bérlése: Port Sarim",
    "Charter-to Port Tyras":            "Hajó bérlése: Port Tyras",
    "Charter-to Prifddinas":            "Hajó bérlése: Prifddinas",
    "Charter-to Shipyard":              "Hajó bérlése: Hajógyár",
    "Charter-to Sunset Coast":          "Hajó bérlése: Naplementepart",
    "Charter-to Tempestus":             "Hajó bérlése: Tempestus",

    # ── Gliders (leave destinations in English) ────────────────────────────────
    "Glider-to Gandius":            "Repülés: Gandius",
    "Glider-to Kar-Hewo":           "Repülés: Kar-Hewo",
    "Glider-to Lemanto Andra":      "Repülés: Lemanto Andra",
    "Glider-to Lemantolly Undri":   "Repülés: Lemantolly Undri",
    "Glider-to Ookookolly Undri":   "Repülés: Ookookolly Undri",
    "Glider-to Sindarpos":          "Repülés: Sindarpos",
    "Glider-to Ta Quir Priw":       "Repülés: Ta Quir Priw",

    # ── Pay variants (farming patches) ────────────────────────────────────────
    "Pay (Celastrus tree)":     "Fizetés (Celastrus fa)",
    "Pay (Fruit tree)":         "Fizetés (Gyümölcsfa)",
    "Pay (Redwood tree)":       "Fizetés (Vörösfenyő)",
    "Pay (Spirit tree)":        "Fizetés (Szellemfa)",
    "Pay (north)":              "Fizetés (észak)",
    "Pay (north-east)":         "Fizetés (észak-kelet)",
    "Pay (north-west)":         "Fizetés (észak-nyugat)",
    "Pay (south)":              "Fizetés (dél)",
    "Pay (south-east)":         "Fizetés (dél-kelet)",
    "Pay (south-west)":         "Fizetés (dél-nyugat)",
    "Pay (tree patch)":         "Fizetés (fafolt)",
    "Pay-toll(10gp)":           "Útdíj fizetése (10gp)",
    "Pay-toll(2-Ecto)":         "Útdíj fizetése (2 Ecto)",

    # ── Misc tagged / dynamic strings ─────────────────────────────────────────
    "Join <colNum0><!ANY_TRANSLATED0></col> channel":  "Csatlakozás: <colNum0><!ANY_TRANSLATED0></col> csatorna",
    "Leave <colNum0><!ANY_TRANSLATED0></col> channel": "Elhagyás: <colNum0><!ANY_TRANSLATED0></col> csatorna",
    "Teleport to <colNum0><!ANY_TRANSLATED0></col>":   "Teleportálás: <colNum0><!ANY_TRANSLATED0></col>",
    "Perform <colNum0>Relic unlock</col>":             "Elvégzés: <colNum0>Ereklye feloldása</col>",
    "Use <colNum0>Special Attack</col>":               "Használat: <colNum0>Speciális támadás</col>",

    # ── Missing patch ─────────────────────────────────────────────────────────
    "Background-music":     "Háttérzene",
    "Burn`":                "Égetés",
    "Call":                 "Hívás",
    "Canyon-count (east)":  "Kanyonszámláló (kelet)",
    "Canyon-count (west)":  "Kanyonszámláló (nyugat)",
    "Cast":                 "Varázslat",
    "Change":               "Csere",
    "Change-clothes":       "Ruhacsere",
    "Claim":                "Átvétel",
    "Clear":                "Törlés",
    "Continue-trek":        "Túra folytatása",
    "Contract":             "Szerződés",
    "Decant":               "Átöntés",
    "Disable":              "Letiltás",
    "Favourite":            "Kedvenc",
    "Fill":                 "Feltöltés",
    "Find":                 "Keresés",
    "Fix":                  "Javítás",
    "Fix-exoskeleton":      "Exoszkeleton javítása",
    "Flick":                "Billegtetés",
    "Flip":                 "Megfordítás",
    "Follow":               "Követés",
    "Forfeit":              "Feladás",
    "Free":                 "Felszabadítás",
    "Friend's house":       "Barát háza",
    "Grapple":              "Megragadás",
    "Guide":                "Útmutató",
    "Heal":                 "Gyógyítás",
    "Help":                 "Segítség",
    "Hide-behind":          "Elbújás mögé",
    "Hide-in":              "Elbújás ide",
    "Inflate":              "Felfújás",
    "Kitten":               "Macskakölök",
    "Last-destination":     "Utolsó célállomás",
    "Lay":                  "Lefektetés",
    "Lift":                 "Emelés",
    "Make":                 "Készítés",
    "Move":                 "Mozgatás",
    "Place":                "Elhelyezés",
    "Place-cell":           "Cella elhelyezése",
    "Play":                 "Játék",
    "Plunder":              "Kifosztás",
    "Pull":                 "Húzás",
    "Pump":                 "Szivattyúzás",
    "Push":                 "Tolás",
    "Ransack":              "Fosztogatás",
    "Refresh":              "Frissítés",
    "Release":              "Elengedés",
    "Reload":               "Újratöltés",
    "Serve":                "Felszolgálás",
    "Shop":                 "Bolt",
    "Smash":                "Szétzúzás",
    "Start":                "Indítás",
    "Store":                "Tárolás",
    "Swipe":                "Húzás",
    "Target":               "Célzás",
    "Thumbs Down":          "Lefele mutató hüvelykujj",
    "Thumbs Up":            "Felfele mutató hüvelykujj",
    "Tickets":              "Jegyek",
    "Viewer":               "Néző",

    # ── Spellbooks ────────────────────────────────────────────────────────────
    "Standard spellbook":   "Alap varázskönyv",
    "Ancient spellbook":    "Ősi varázskönyv",
    "Lunar spellbook":      "Hold varázskönyv",
    "Arceuus spellbook":    "Arceuus varázskönyv",
    "Ancients":             "Ősök",
    "Lunar":                "Hold",

    # ── Group actions ─────────────────────────────────────────────────────────
    "Group: Choose":        "Csoport: Választás",
    "Group: Previous":      "Csoport: Előző",
}

# ── Pattern-based translations ────────────────────────────────────────────────
# These handle the many "Last-destination (XYZ)" and "Ring-last-destination (XYZ)" entries.
def apply_pattern_translation(source: str) -> str | None:
    if re.match(r'^Last-destination \([A-Z]+\)$', source):
        code = re.search(r'\(([A-Z]+)\)', source).group(1)
        return f"Utolsó célállomás ({code})"
    if re.match(r'^Ring-last-destination \([A-Z]+\)$', source):
        code = re.search(r'\(([A-Z]+)\)', source).group(1)
        return f"Gyűrű – utolsó célállomás ({code})"
    return None


def apply_translations():
    tree = etree.parse(XLIFF_PATH)
    body = tree.find(f'.//{{{NS}}}body')
    translated = 0
    kept_english = 0
    missing = []

    for unit in body.findall(f'.//{{{NS}}}trans-unit'):
        source_el = unit.find(f'{{{NS}}}source')
        target_el = unit.find(f'{{{NS}}}target')
        if source_el is None or target_el is None:
            continue

        source = source_el.text or ""

        # Already has a translation — skip
        if target_el.text and target_el.text.strip():
            continue

        # OSRS proper noun — copy source as-is
        if source in KEEP_ENGLISH:
            target_el.text = source
            kept_english += 1
            continue

        # Exact match in dict
        if source in TRANSLATIONS:
            target_el.text = TRANSLATIONS[source]
            translated += 1
            continue

        # Pattern match
        pattern_result = apply_pattern_translation(source)
        if pattern_result:
            target_el.text = pattern_result
            translated += 1
            continue

        missing.append(source)

    tree.write(XLIFF_PATH, pretty_print=True, xml_declaration=True, encoding='UTF-8')
    print(f"Done: {translated} translated, {kept_english} kept in English, {len(missing)} still missing.")
    if missing:
        print(f"\nMissing translations ({len(missing)}):")
        for m in sorted(set(missing)):
            print(f"  {repr(m)}")


if __name__ == '__main__':
    apply_translations()
